### PR TITLE
Feat/replace update attributes by update

### LINKED ISSUE #1: update_attributes is deprecated
`rails db:seed` on rails 6.0 gives me:

````
DEPRECATION WARNING: update_attributes is deprecated and will be removed from Rails 6.1 (please, use update instead) (called from <top (required)> at db/seeds.rb:2)
````

Simply changing `update_attributes` to `update` in `seed_box.rb` seems to solve the problem for me.

### PR DESCRIPTION
**Pull request by koffeinfrei**
`update_attributes` is deprecated. Replace `update_attributes` by `update`.

Fixes https://github.com/panter/seed_box/issues/1

### CODE REVIEW

**Comment by koffeinfrei** [comment]
Any panters out there to have a look at this?

**Comment by panterch** [comment]
> Any panters out there to have a look at this?

lgtm ;-)

**Comment by koffeinfrei** [comment]
@panterch You'll also have to merge and release the new gem version :smile_cat:

**Comment by alesrosina** [comment]
@koffeinfrei releasing new gem version is actually on you, since you're the owner on rubygems.org :) Or transfer ownershipt to user panter if you dont want to maintain it.

**Comment by koffeinfrei** [comment]
@alesrosina Yes, although I can't bump the version since I'm missing permission on this repo. Would you mind adding me as a contributor to this repo?

**Comment by alesrosina** [comment]
@koffeinfrei there, you're contributor. But you already bumped a version in this merge request here, so it should be fine actually

**Comment by koffeinfrei** [comment]
> there, you're contributor.

Thanks :+1: 

> But you already bumped a version in this merge request here, so it should be fine actually

Right :blush: 

Anyway, new gem version published.

**Pull request merged**
